configure.ac: Add "foreign"
Upgrade to newer autotools syntax and supply "foreign" to automake
to prevent autoreconf failing with:
error: required file './NEWS' not found
etc.